name: moz_mobile_messaging
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^9.6.5
  flutter_bloc: 7.2.0
  equatable: ^2.0.3
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  flutter_emoji: ^2.4.0
  intl: ^0.17.0
  cached_network_image: ^3.2.0
  font_awesome_flutter: ^9.2.0
  path: ^1.8.1
  flutter_image_compress: ^1.0.0-nullsafety
  flutter_neumorphic: ^3.2.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  firebase_messaging: ^11.2.6
  cloud_firestore: ^3.1.8
  firebase_storage: ^10.2.7
  country_pickers: 2.0.0
  flutter_local_notifications: ^8.2.0
  http: ^0.13.4
  cupertino_icons: ^1.0.2
  permission_handler: ^9.2.0
  contacts_service: ^0.6.3
  


  flutter_lints: ^1.0.0


flutter:

 
  uses-material-design: true

 
